<?php

$parameter['id'] = 800;
$parameter['name'] = 'push';
$parameter['label'] = 'e-mailing';
$parameter['table_prefix'] = 'psh_*';

$parameter['back'] = array('campagnes' => 'campaign.home',
                           'messages' => 'body.home',
                           'bases' => 'base.home',
                           'newsletters' => 'newsletter.home',
                           'mailings' => 'mailing.home');
