<?php

$parameter['id'] = 1430;
$parameter['name'] = 'ntd';
$parameter['label'] = 'Net Declaration';
$parameter['table_prefix'] = 'ntd_*';
$parameter['back'] = array('Adhérents' => 'adherent.home',
                           'Partenaires' => 'partenaire.home', 
                           'Déclarations' => 'declaration.home',
                           'Souscriptions' => 'souscription.home',
                           'Suivis' => 'suivi.home',
                           '---',
                           'Factures' => 'facture.home',
                           'Paiements' => 'payment.home',
                           '---',
                           'Catégories de Service' => 'servicetype.home',
                           'services' => 'service.home',
                           'tarifs' => 'tarif.home',
                           'Suivis payants' => 'suivipayant.home',
                           'Type de message EDI' => 'edimessagetype.home',
                           'Forfaits Dossier' => 'forfait.home',
                           'Moyens de paiements' => 'method.home',
                           '---',
                           'Millesimes' => 'millesime.home',
                           'Types de Déclaration' => 'dectype.home',
                           'Types de Formulaire' => 'formulairetype.home',
                           'Dictionnaire EDI' => 'dicoedi.home',
                           '---',
                           'Dossier de greffe' => 'greffedossier.home',
                           'Dépôt de greffe' => 'greffe.home',
                           'Commune' => 'greffecommune.home',
                           '---',
                           'Page Accueil' => 'homepage.editor'
);
