<?php

$form["cvae1329def_20170101"] = array(
  'AA' => array('type' => 'number'),
  'AB' => array('type' => 'number'),
  'AC' => array('type' => 'pourcentage'),
  'AD' => array('type' => 'number'),
  'AE' => array('type' => 'alphabetic', 'length' => 9),
  'BA' => array('type' => 'number'),
  'BB' => array('type' => 'number'),
  'BC' => array('type' => 'checkbox', 'value' => '1'),
  'CA' => array('type' => 'number'),
  'CB' => array('type' => 'number'),
  'DA' => array('type' => 'number'),
  'DB' => array('type' => 'number'),
  'EA' => array('type' => 'number'),
  'EB' => array('type' => 'number'),
  'EC' => array('type' => 'number'),
  'ED' => array('type' => 'number'),
  'GA' => array('type' => 'checkbox', 'value' => 1),
  'GB' => array('type' => 'number'),
  'GC' => array('type' => 'number'),
  'GD' => array('type' => 'number'),
  'GE' => array('type' => 'number'),
  'HA' => array('type' => 'number'),
  'HB' => array('type' => 'number'),
  'HC' => array('type' => 'number'),
  'HD' => array('type' => 'number'),
  'JA' => array('type' => 'number'),
  'JE' => array('type' => 'number'),
  'JK' => array('type' => 'number'),
  'KA' => array('type' => 'number'),
  'KB' => array('type' => 'number'),
);


foreach ($form["cvae1329def_20170101"] as $fieldname => $data) {
  $form["cvae1329def_20170101"][$fieldname]['operations'][]['assert'] = 'cvae1329def_20170101';
}
