<?php

$operations = array();

$form['is2573sd'] = array(

  'AA' => array(
    'type' => 'checkbox',
  ),
  'AB' => array( 
    'type' => 'data-select',
    'options' => 'crb'
  ),
  'AC' => array(
    'type' => 'date-ssaa'
  ),
  'AD' => array(
    'type' => 'number',
  ),
  'AE' => array(
    'type' => 'number',
  ),
  'AF' => array(
    'type' => 'number',
  ),
  'AG' => array(
    'type' => 'number',
  ),
  'AH' => array(
    'type' => 'data-select',
    'options' => 'col'
  ),
  'AI' => array(
    'type' => 'date-ssaammjj'
  ),
  'BA' => array(
    'length' => 9,
    'type' => 'alphabetic',
  ),
  'BB' => array(
    'type' => 'date-ssaammjj'
  ),
  'BC' => array(
    'type' => 'date-ssaammjj'
  ),
  'BD' => array(
    'length' => 9,
    'type' => 'alphabetic',
  ),
  'BE' => array(
    'type' => 'number',
  ),
  'CA' => array(
    'length' => 9,
    'type' => 'alphabetic',
  ),
  'CB' => array(
    'type' => 'data-select',
    'options' => 'ctr'
  ),
  'CC' => array(
    'type' => 'date-ssaammjj'
  ),
  'CD' => array(
    'type' => 'date-ssaammjj'
  ),
  'CE' => array(
    'length' => 9,
    'type' => 'alphabetic',
  ),
  'CF' => array(
    'type' => 'number',
  ),

);
