<?php

$fields = array('BA' => array('type_segment' => 'MOA',
                              'composite' => 'C516',
                              'simple' => '5004',
),
                'CA' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DA' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EA' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FA' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GA' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BB' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CB' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DB' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EB' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FB' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GB' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BC' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CC' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DC' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EC' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FC' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GC' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BD' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CD' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DD' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'ED' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FD' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GD' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BE' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CE' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DE' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EE' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FE' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GE' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BF' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CF' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DF' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EF' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FF' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GF' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BG' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CG' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DG' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EG' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FG' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GG' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BH' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CH' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DH' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EH' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FH' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GH' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BJ' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CJ' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DJ' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EJ' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FJ' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GJ' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'BK' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'CK' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'DK' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'EK' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'FK' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'GK' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'HA' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'HB' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'HC' =>
                array(
                  'type_segment' => 'MOA',
                  'composite' => 'C516',
                  'simple' => '5004',
                ),
                'HD' =>
                array(
                  'type_segment' => 'CCI',
                  'composite' => 'C889',
                  'simple' => '7111',
                ),
);


$calculs = array(
  array('method' => 'evaluate', 'args' => array('formula' => '@BK=@BA+@BB+@BC+@BD+@BE+@BF+@BG+@BH+@BJ')),
  array('method' => 'evaluate', 'args' => array('formula' => '@CK=@CA+@CB+@CC+@CD+@CE+@CF+@CG+@CH+@CJ')),
  array('method' => 'evaluate', 'args' => array('formula' => '@DK=@DA+@DB+@DC+@DD+@DE+@DF+@DG+@DH+@DJ')),
  array('method' => 'evaluate', 'args' => array('formula' => '@EK=@EA+@EB+@EC+@ED+@EE+@EF+@EG+@EH+@EJ')),
  array('method' => 'evaluate', 'args' => array('formula' => '@FK=@FA+@FB+@FC+@FD+@FE+@FF+@FG+@FH+@FJ')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GK=@GA+@GB+@GC+@GD+@GE+@GF+@GG+@GH+@GJ')),

  array('method' => 'evaluate', 'args' => array('formula' => '@GA=@BA-@CA-@FA')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GB=@BB-@CB-@FB')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GC=@BC-@CC-@FC')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GD=@BD-@CD-@FD')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GE=@BE-@CE-@FE')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GF=@BF-@CF-@FF')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GG=@BG-@CG-@FG')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GH=@BH-@CH-@FH')),
  array('method' => 'evaluate', 'args' => array('formula' => '@GJ=@BJ-@CJ-@FJ')),  
                     
  array('method' => 'evaluate', 'args' => array('formula' => '@HC=@HA-@HB')),
);
