<?php

$parameter['id'] = 350;
$parameter['name'] = 'community';
$parameter['label'] = 'communauté';
$parameter['table_prefix'] = 'cty_*';
$parameter['back'] = array('utilisateurs' => 'user.home',
                           //'individus' => 'person.home',
                           //'privilèges' => 'privilege.home',
                           //'avis' => 'notice.home',
                           //'origines' => 'origin.home',
                           //'offres' => 'offer.home'
);



