<?php

$parameter['id'] = 1;
$parameter['name'] = 'core';
$parameter['label'] = 'système';
$parameter['table_prefix'] = 'sys_*';
$parameter['back'] = array('paramètres' => 'parameter.home',
                           'pagelets' => 'pagelet.home',
                           'pays' => 'country.home',
                           'administrateurs' => 'admin.home',
                           'droits' => 'policy.home',
                           'intérêts' => 'interest.home',
                           'rubriques' => 'heading.home',
                           'styles' => 'stylesheet.home',
                           'propriétés' => 'property.home',
                           'contacts' => 'contact.home',
                           'actions' => 'action.home',
                           'redirections' => 'redirection.home',
                           'mots interdits' => 'badword.home',
                           'emails' => 'email.home',
                           'tags' => 'tag.home',
                           'zones' => 'area.home');

