<?php

$parameter['id'] = 400;
$parameter['name'] = 'cms';
$parameter['label'] = 'cms';
$parameter['back'] = array(//'dossiers' => 'paper.home',
                           'articles' => 'article.home',
                           //'faq' => 'faq.home',
                           'pages' => 'page.home',
                           'fragments' => 'snippet.home',
                           'phrases' => 'string.home',
                           //'glossaires' => 'glossary.home',
                           'courriers' => 'letter.home',
                           //'slideshows' => 'slideshow.home'
);
$parameter['table_prefix'] = 'cms_*';